### ISSUE TITLE
Invalid License

### ISSUE THREAD

**Issue by uap-universe** [mindspank/GoogleMaps-Cluster-QV11#1]
Since plugins in QlikView are not executed by using fork/exec, you cannot use the GPL license for a QlikView Plugin. 

See also the GPL FAQ under this link:
http://www.gnu.org/licenses/gpl-faq.html#GPLPluginsInNF

**Comment by mindspank** [comment]
Any specific license you would like to see instead?

**Comment by uap-universe** [comment]
It's not up to me to decide what license you would use.

You could aim for the BSD License or the MIT License, if you just want to have _any_ license that is compatible.

**Comment by mindspank** [comment]
No but since you raised an issue I assumed you were looking for something specific.
I don't actively maintain this extension anymore so I'm open to anything, so I'll just throw MIT in there instead
